version: '2'

services:
  web:
    image: spiritualisms-www
    build:
      context: .
      dockerfile: docker/www
    links:
      - "redis:cache"
      - "couchdb:db"
    ports:
     - "3000:3000"
  api:
    image: spiritualisms-api
    build:
      context: .
      dockerfile: docker/api
    links:
      - "redis:cache"
      - "couchdb:db"
    ports:
     - "3001:3001"
  redis:
    image: spiritualisms-redis
    build:
      context: .
      dockerfile: docker/redis
    ports:
     - "6379:6379"
  couchdb:
    image: spiritualisms-couchdb
    build:
      context: .
      dockerfile: docker/couchdb
    ports:
     - "5984:5984"
    volumes:
      - /usr/local/var/lib/couchdb:/usr/local/var/lib/couchdb
