version: '2'

services:
  nginx:
    image: spiritualisms-nginx
    build:
      context: .
      dockerfile: docker/nginx
    links:
      - "web:www.spiritualisms.org"
      - "api:api.spiritualisms.org"
      - "file:file.spiritualisms.org"
    ports:
     - "80:80"
  web:
    image: spiritualisms-www
    build:
      context: .
      dockerfile: docker/www
    environment:
      SPIRITUALISMS_COUCHDB_USER: "$SPIRITUALISMS_COUCHDB_USER"
      SPIRITUALISMS_COUCHDB_PASS: "$SPIRITUALISMS_COUCHDB_PASS"
    links:
      - "redis:cache.spiritualisms.org"
      - "couchdb:db.spiritualisms.org"
    ports:
     - "3000:3000"
  api:
    image: spiritualisms-api
    build:
      context: .
      dockerfile: docker/api
    environment:
      SPIRITUALISMS_COUCHDB_USER: "$SPIRITUALISMS_COUCHDB_USER"
      SPIRITUALISMS_COUCHDB_PASS: "$SPIRITUALISMS_COUCHDB_PASS"
    links:
      - "redis:cache.spiritualisms.org"
      - "couchdb:db.spiritualisms.org"
    ports:
     - "3001:3001"
  file:
    image: spiritualisms-file
    build:
      context: .
      dockerfile: docker/file
    environment:
      SPIRITUALISMS_COUCHDB_USER: "$SPIRITUALISMS_COUCHDB_USER"
      SPIRITUALISMS_COUCHDB_PASS: "$SPIRITUALISMS_COUCHDB_PASS"
    links:
      - "redis:cache.spiritualisms.org"
      - "couchdb:db.spiritualisms.org"
    ports:
     - "3002:3002"
  redis:
    image: spiritualisms-redis
    build:
      context: .
      dockerfile: docker/redis
    ports:
     - "6379:6379"
    volumes:
      - /opt/redis/data:/opt/redis/data
  couchdb:
    image: spiritualisms-couchdb
    build:
      context: .
      dockerfile: docker/couchdb
    ports:
     - "5984:5984"
    volumes:
      - /opt/couchdb/data:/opt/couchdb/data
