version: '2'

services:
  web:
    image: spiritualisms-www
    build:
      context: .
      dockerfile: docker/www
    ports:
     - "3000:3000"
  api:
    image: spiritualisms-api
    build:
      context: .
      dockerfile: docker/api
    ports:
     - "3001:3001"
  redis:
    image: spiritualisms-redis
    build:
      context: .
      dockerfile: docker/redis
