version: '2'

services:
  nginx:
    image: spiritualisms-nginx
    build:
      context: .
      dockerfile: docker/nginx
    links:
      - "web:www.spiritualisms.org"
      - "api:api.spiritualisms.org"
      - "file:file.spiritualisms.org"
    ports:
     - "80:80"
  web:
    image: spiritualisms-www
    build:
      context: .
      dockerfile: docker/www
    links:
      - "redis:cache.spiritualisms.org"
      - "couchdb:db.spiritualisms.org"
    ports:
     - "3000:3000"
  api:
    image: spiritualisms-api
    build:
      context: .
      dockerfile: docker/api
    links:
      - "redis:cache.spiritualisms.org"
      - "couchdb:db.spiritualisms.org"
    ports:
     - "3001:3001"
  file:
    image: spiritualisms-file
    build:
      context: .
      dockerfile: docker/file
    links:
      - "redis:cache.spiritualisms.org"
      - "couchdb:db.spiritualisms.org"
    ports:
     - "3002:3002"
    volumes:
      - ./www/public/files:/usr/src/www/public/files
  redis:
    image: spiritualisms-redis
    build:
      context: .
      dockerfile: docker/redis
    ports:
     - "6379:6379"
  couchdb:
    image: spiritualisms-couchdb
    build:
      context: .
      dockerfile: docker/couchdb
    ports:
     - "5984:5984"
    volumes:
      - /usr/local/var/lib/couchdb:/usr/local/var/lib/couchdb
