lang = "en"
host = "spiritualisms.org"

[build]
rewrite-index = true
extend = ["html", "json"]

[page]
description = ""
keywords = ""
authors = [ { name = "muji", url = "https://tmpfs.org" } ]

[pages."index.html"]
title = "Home"
query = {name = "quotes", index = "all", include_docs = true, unique = true}

[pages."quotes/index.html"]
query = {name = "quotes", index = "all", include_docs = true, unique = true}

[pages."quotes/item.html"]
title = "Quote"
query = {name = "quotes", index = "all", each = true, include_docs = true, unique = true}

[pages."quotes/item.json"]
rewrite-index = false
standalone = true
query = {name = "quotes", index = "all", each = true, include_docs = true, unique = true}

[pages."quotes/index.json"]
rewrite-index = false
standalone = true
query = {name = "quotes", index = "all", keys = "name", unique = true}

[pages."authors/index.html"]
query = {name = "quotes", index = "author", include_docs = true}

[pages."authors/item.html"]
title = "Author"
query = {name = "quotes", index = "author", each = true, include_docs = true}

[pages."tags/index.html"]
query = {name = "quotes", index = "tags", include_docs = true}

[pages."tags/item.html"]
title = "Tag"
query = {name = "quotes", index = "tags", each = true, include_docs = true}

[pages."404.html"]
standalone = true
rewrite-index = false

[publish.aws]
region = "ap-southeast-1"
credentials = "tmpfs"

[publish.aws.environments.stage]
bucket = "stage.spiritualisms.org"

[publish.aws.environments.production]
bucket = "spiritualisms.org"
