lang = "en"
host = "spiritualisms.org"

[styles]
main = ["/assets/css/style.css"]

[build]
rewrite-index = true
extend = ["html", "json"]

[db.load.quotes]
type = "json"
provider = "files"
from = "data/quotes"

[db.load.quotes.on.all]
key = "*"

[db.load.quotes.on.author]
key = "author"

[db.load.quotes.on.tags]
key = "tags"

[page]
description = ""
keywords = ""
authors = [ { name = "Muji", link = "https://tmpfs.org" } ]

[pages."index.html".query]
name = "quotes"
index = "all"
include-docs = true

[pages."quotes/index.html".query]
name = "quotes"
index = "all"
include-docs = true

[pages."quotes/item.html".query]
name = "quotes"
index = "all"
each = true
include-docs = true

[pages."quotes/item.json"]
rewrite-index = false
standalone = true

[pages."quotes/item.json".query]
name = "quotes"
index = "all"
each = true
include-docs = true

[pages."quotes/index.json"]
rewrite-index = false
standalone = true

[pages."quotes/index.json".query]
name = "quotes"
index = "all"
keys = true
key-type = "id"

[pages."authors/index.html".query]
name = "quotes"
index = "author"
include-docs = true
group = {path = "author"}

[pages."authors/item.html".query]
name = "quotes"
index = "author"
each = true
include-docs = true
group = {path = "author"}

[pages."tags/index.html".query]
name = "quotes"
index = "tags"
include-docs = true
group = {path = "tags", expand = true}

[pages."tags/item.html".query]
name = "quotes"
index = "tags"
each = true
include-docs = true
group = {path = "tags", expand = true}

[pages."404.html"]
standalone = true
rewrite-index = false

[publish.aws]
region = "ap-southeast-1"
credentials = "tmpfs"

[publish.aws.environments.stage]
bucket = "stage.spiritualisms.org"

[publish.aws.environments.production]
bucket = "spiritualisms.org"
