lang = "en"
host = "spiritualisms.org"

[build]
source = "site"
target = "build"

[extension]
render = ["md", "html", "json"]
map = {md = "html"}
markdown = ["md"]

[page]
description = ""
keywords = ""
author = { name = "muji", url = "https://tmpfs.org" }

