[build]
source = "site"
target = "build"
strict = true
html_extension = false
follow_links = false

[extension]
render = ["md", "html", "json"]
map = {md = "html"}
markdown = ["md"]

[serve]
host = "localhost"
port = 3000
