lang = "en"
host = "spiritualisms.org"

[build]
rewrite-index = true
render = ["html", "json"]

[page]
description = ""
keywords = ""
author = { name = "muji", url = "https://tmpfs.org" }

[publish.aws]
region = "ap-southeast-1"
credentials = "tmpfs"

[publish.aws.environments.stage]
bucket = "stage.spiritualisms.org"

[publish.aws.environments.production]
bucket = "spiritualisms.org"
