[site]
description = ""
keywords = ""
author = "muji"
author_url = "https://tmpfs.org"

["/"]
title = "Home"
query = {name = "quotes", index = "all", include_docs = true}

["quotes/"]
query = {name = "quotes", index = "all", include_docs = true}

["quotes/item"]
title = "Quote"
query = {name = "quotes", index = "all", each = true, include_docs = true}

["quotes/item.json"]
clean = false
standalone = true
query = {name = "quotes", index = "all", each = true, include_docs = true}

["quotes/index.json"]
clean = false
standalone = true
query = {name = "quotes", index = "all", keys = true}

["authors/"]
query = {name = "quotes", index = "author", include_docs = true}

["authors/item"]
title = "Author"
query = {name = "quotes", index = "author", each = true, include_docs = true}

["tags/"]
query = {name = "quotes", index = "tags", include_docs = true}

["tags/item"]
title = "Tag"
query = {name = "quotes", index = "tags", each = true, include_docs = true}

["404.html"]
standalone = false
clean = false

