[site]
description = ""
keywords = ""
author = "muji"
author_url = "https://tmpfs.org"

["/"]
title = "Home"

["404.html"]
standalone = false
clean = false

["google17a6906a04e2c5e4.html"]
standalone = true
clean = false

