[site]
description = ""
keywords = ""
author = "muji"
author_url = "https://tmpfs.org"

["/"]
title = "Home"
generator = {name = "quotes", index = "all", parameter = "documents"}

["quotes/"]
generator = {name = "quotes", index = "all", parameter = "documents"}

["quotes/item"]
title = "Quote"
generator = {name = "quotes", index = "all", parameter = "document", each = true}

["authors/"]
generator = {name = "quotes", index = "author", parameter = "documents", include_docs = true}

["404.html"]
standalone = false
clean = false

#["google17a6906a04e2c5e4.html"]
#standalone = true
#clean = false

