[site]
description = ""
keywords = ""
author = "muji"
author_url = "https://tmpfs.org"

["/"]
title = "Home"
generator = {name = "quotes", index = "all", parameter = "documents", include_docs = true}

["quotes/"]
generator = {name = "quotes", index = "all", parameter = "documents", include_docs = true}

["quotes/item"]
title = "Quote"
generator = {name = "quotes", index = "all", each = true, include_docs = true}

["quotes/item.json"]
clean = false
standalone = true
generator = {name = "quotes", index = "all", each = true, include_docs = true}

["quotes/index.json"]
clean = false
standalone = true
generator = {name = "quotes", index = "all", parameter = "ids", keys = true}

["authors/"]
generator = {name = "quotes", index = "author", parameter = "documents", include_docs = true}

["authors/item"]
title = "Author"
generator = {name = "quotes", index = "author", each = true, include_docs = true}

["tags/"]
generator = {name = "quotes", index = "tags", parameter = "documents", include_docs = true}

["tags/item"]
title = "Tag"
generator = {name = "quotes", index = "tags", each = true, include_docs = true}

["404.html"]
standalone = false
clean = false

#["google17a6906a04e2c5e4.html"]
#standalone = true
#clean = false

